# Generated by Django 3.2 on 2023-01-31 12:54

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Укажите год выпуска произведения', validators=[reviews.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
