# Generated by Django 3.2 on 2023-01-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
