# Generated by Django 3.2 on 2023-01-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_year'),
        ('reviews', '0020_alter_review_score'),
    ]

    operations = [
    ]
